# Generated by Django 4.2.27 on 2026-06-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('sales_weekly_digest', 'Sales Weekly Digest')], default='sales_weekly_digest', max_length=50)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='reports.report')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('report', 'week_start')},
            },
        ),
    ]
