# Generated by Django 4.2.27 on 2026-06-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.CharField(blank=True, default='Sales Weekly Digest - System Generated', max_length=255),
        ),
    ]
