# Generated by Django 4.2.27 on 2026-06-28 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_send_weekday', models.PositiveSmallIntegerField(default=0)),
                ('default_send_time', models.TimeField(default=datetime.time(6, 0))),
            ],
            options={
                'verbose_name': 'Report setting',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='send_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='send_weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
