# Generated by Django 4.2.27 on 2026-06-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_reportsetting_report_send_time_report_send_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('send_now', 'Send now'), ('test', 'Test')], max_length=20)),
                ('week_label', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('recipients', models.JSONField(default=list)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_events', to='reports.report')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_send_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
