# Generated by Django 4.2.27 on 2026-06-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_daily_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_in_dropdown',
            field=models.BooleanField(default=True),
        ),
    ]
