# Generated by Django 4.2.27 on 2026-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('general_new', 'General New'), ('general_renewal', 'General Renewal'), ('general_claim', 'General Claim'), ('motor_new', 'Motor New'), ('motor_renewal', 'Motor Renewal'), ('motor_claim', 'Motor Claim'), ('sales', 'Sales')], max_length=50),
        ),
    ]
