# Generated by Django 4.2.27 on 2026-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_rolemodulepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('general_new', 'General New'), ('general_renewal', 'General Renewal'), ('general_claim', 'General Claim'), ('motor_new', 'Motor New'), ('motor_renewal', 'Motor Renewal'), ('motor_claim', 'Motor Claim'), ('sales_premium_data', 'Sales Premium Data'), ('sales_kpi', 'Sales KPI'), ('marine_new', 'Marine New'), ('marine_renewal', 'Marine Renewal'), ('medical_claim', 'Medical Claim')], max_length=50),
        ),
    ]
