# Generated by Django 4.2.27 on 2026-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_add_settings_module_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('general_new', 'General New'), ('general_renewal', 'General Renewal'), ('general_claim', 'General Claim'), ('motor_new', 'Motor New'), ('motor_renewal', 'Motor Renewal'), ('motor_claim', 'Motor Claim'), ('motor_fleet_new', 'Motor Fleet New'), ('motor_fleet_renewal', 'Motor Fleet Renewal'), ('sales_kpi', 'Sales KPI'), ('marine_new', 'Marine New'), ('marine_renewal', 'Marine Renewal'), ('medical_claim', 'Medical Claim'), ('settings', 'Settings')], max_length=50),
        ),
    ]
