# Generated by Django 4.2.27 on 2026-05-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_alter_rolemodulepermission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_hod',
            field=models.BooleanField(default=False, help_text='Head of Department — oversight role: sees all team data, cannot add/edit entries.'),
        ),
    ]
