# Generated by Django 4.2.27 on 2026-01-07 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorRenewalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotations', models.PositiveIntegerField()),
                ('retention', models.PositiveIntegerField()),
                ('tat', models.PositiveIntegerField(verbose_name='TAT')),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor Renewal Entry',
                'verbose_name_plural': 'Motor Renewal Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorNewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotations', models.PositiveIntegerField()),
                ('quotes_revised', models.PositiveIntegerField()),
                ('tat', models.PositiveIntegerField(verbose_name='TAT')),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor New Entry',
                'verbose_name_plural': 'Motor New Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorClaimEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_claims', models.PositiveIntegerField()),
                ('claims_closed', models.PositiveIntegerField()),
                ('pending_cases', models.PositiveIntegerField()),
                ('tat', models.PositiveIntegerField(verbose_name='TAT')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor Claim Entry',
                'verbose_name_plural': 'Motor Claim Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralRenewalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotations', models.PositiveIntegerField()),
                ('quotes_revised', models.PositiveIntegerField()),
                ('quotes_converted', models.PositiveIntegerField()),
                ('tat', models.PositiveIntegerField(verbose_name='TAT')),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Renewal Entry',
                'verbose_name_plural': 'General Renewal Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralNewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotations', models.PositiveIntegerField()),
                ('quotes_revised', models.PositiveIntegerField()),
                ('quotes_converted', models.PositiveIntegerField()),
                ('tat', models.PositiveIntegerField(verbose_name='TAT')),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General New Entry',
                'verbose_name_plural': 'General New Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
    ]
