# Generated by Django 4.2.27 on 2026-01-29 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_booked_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth_month_wise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth_year_wise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead_to_quote_ratio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quote_to_conversion_ratio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('new_clients_acquired', models.PositiveIntegerField()),
                ('client_retention_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Entry',
                'verbose_name_plural': 'Sales Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
    ]
