# Generated by Django 4.2.27 on 2026-01-30 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0002_salesentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesKPIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leads_to_ops_team', models.PositiveIntegerField()),
                ('quotes_from_ops_team', models.PositiveIntegerField()),
                ('quotes_to_client', models.PositiveIntegerField()),
                ('total_conversions', models.PositiveIntegerField()),
                ('existing_clients', models.PositiveIntegerField()),
                ('existing_clients_closed', models.PositiveIntegerField()),
                ('new_clients_acquired', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales KPI Entry',
                'verbose_name_plural': 'Sales KPI Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPremiumDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_booked_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target', models.DecimalField(decimal_places=2, max_digits=15)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Premium Data Entry',
                'verbose_name_plural': 'Sales Premium Data Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SalesEntry',
        ),
    ]
