# Generated by Django 4.2.27 on 2026-03-07 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0003_saleskpientry_salespremiumdataentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineRenewalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_renewal_quotes_assigned', models.PositiveIntegerField()),
                ('gross_booked_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quotes_created', models.PositiveIntegerField()),
                ('renewal_policies_issued', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marine Renewal Entry',
                'verbose_name_plural': 'Marine Renewal Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarineNewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_booked_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quotes_created', models.PositiveIntegerField()),
                ('new_clients_acquired', models.PositiveIntegerField()),
                ('new_policies_issued', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marine New Entry',
                'verbose_name_plural': 'Marine New Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
    ]
