# Generated by Django 4.2.27 on 2026-03-16 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0004_marinerenewalentry_marinenewentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalClaimEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('claims_opened', 'Claims Opened'), ('claims_pending', 'Claims Pending'), ('claims_resolved', 'Claims Resolved')], max_length=20)),
                ('claims_opened', models.PositiveIntegerField()),
                ('claims_pending', models.PositiveIntegerField()),
                ('claims_resolved', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Claim Entry',
                'verbose_name_plural': 'Medical Claim Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
    ]
