# Generated by Django 4.2.27 on 2026-03-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_medicalclaimentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalclaimentry',
            name='claims_opened',
        ),
        migrations.RemoveField(
            model_name='medicalclaimentry',
            name='claims_pending',
        ),
        migrations.RemoveField(
            model_name='medicalclaimentry',
            name='claims_resolved',
        ),
    ]
