# Generated by Django 4.2.27 on 2026-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_update_motorclaimentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnewentry',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='generalnewentry',
            name='tat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TAT'),
        ),
    ]
