# Generated by Django 4.2.27 on 2026-03-28 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0008_general_new_optional_tat_accuracy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generalnewentry',
            unique_together={('added_by', 'date')},
        ),
    ]
