# Generated by Django 4.2.27 on 2026-04-13 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0010_merge_sales_modules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generalnewentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='medicalclaimentry',
            name='status',
            field=models.CharField(choices=[('claims_opened', 'Claims Opened'), ('claims_pending', 'Claims Pending'), ('claims_resolved', 'Claims Resolved'), ('claims_rejected', 'Claims Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesmonthlytarget',
            name='premium_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MedicalClaimStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('claims_opened', 'Claims Opened'), ('claims_pending', 'Claims Pending'), ('claims_resolved', 'Claims Resolved'), ('claims_rejected', 'Claims Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('claims_opened', 'Claims Opened'), ('claims_pending', 'Claims Pending'), ('claims_resolved', 'Claims Resolved'), ('claims_rejected', 'Claims Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_claim_status_changes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='entries.medicalclaimentry')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
