# Generated by Django 4.2.27 on 2026-04-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0014_generalnewentry_tat_accuracy_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalrenewalentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marinenewentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marinerenewalentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalclaimentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorclaimentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motornewentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorrenewalentry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleskpientry',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
