# Generated by Django 4.2.27 on 2026-05-14 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0027_general_renewal_revamp_and_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorFleetNewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200)),
                ('chassis_no', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('quotes_compared', models.PositiveIntegerField(default=0)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motor_fleet_new_enquiries_as_agent', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor Fleet New Entry',
                'verbose_name_plural': 'Motor Fleet New Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotorFleetRenewalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200)),
                ('chassis_no', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost')], default='new', max_length=20)),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('quotes_compared', models.PositiveIntegerField(default=0)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motor_fleet_renewal_enquiries_as_agent', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_on_behalf_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor Fleet Renewal Entry',
                'verbose_name_plural': 'Motor Fleet Renewal Entries',
                'ordering': ['-date', '-added_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pibsequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MotorFleetRenewalStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_fleet_renewal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='entries.motorfleetrenewalentry')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MotorFleetNewStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New Enquiry'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_fleet_new_status_changes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='entries.motorfleetnewentry')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MotorFleetRenewalMonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('calculated_date', models.DateField(db_index=True)),
                ('clients_assigned', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_fleet_renewal_monthly_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
