# Generated by Django 4.2.27 on 2026-05-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0036_sales_kpi_per_ticket_revamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewentry',
            name='converted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='generalrenewalentry',
            name='converted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='motorfleetnewentry',
            name='converted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='motorfleetrenewalentry',
            name='converted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='motornewentry',
            name='converted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='motorrenewalentry',
            name='converted_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
