# Generated by Django 4.2.27 on 2026-06-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0038_sales_clients_assigned_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorfleetnewentry',
            name='class_of_enquiry',
            field=models.CharField(blank=True, choices=[('comprehensive', 'Comprehensive'), ('tpl', 'TPL')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='motorfleetnewentry',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_fleet_new_entries', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorfleetrenewalentry',
            name='class_of_enquiry',
            field=models.CharField(blank=True, choices=[('comprehensive', 'Comprehensive'), ('tpl', 'TPL')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='motorfleetrenewalentry',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_fleet_renewal_entries', to='entries.insurancecompany'),
        ),
    ]
