# Generated by Django 4.2.27 on 2026-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0040_sales_status_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalnewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generalnewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetnewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetnewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetnewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motornewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='motornewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motornewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
    ]
