# Generated by Django 4.2.27 on 2026-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0041_alter_generalnewentry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorfleetnewentry',
            name='potential_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
