# Generated by Django 4.2.27 on 2026-07-03 06:31

from django.db import migrations, models


# TED-592: the six enquiry modules gaining a compared-insurers M2M.
_ENQUIRY_MODELS = [
    'GeneralNewEntry', 'GeneralRenewalEntry',
    'MotorNewEntry', 'MotorRenewalEntry',
    'MotorFleetNewEntry', 'MotorFleetRenewalEntry',
]


def backfill_compared_insurers(apps, schema_editor):
    """Seed the new compared-insurers M2M from each existing enquiry's single
    `insurance_company` FK.

    The create modal is switching from a single-select to a multi-select, so
    every historical enquiry's chosen insurer is preserved as its first
    compared insurer. Purely additive — this only inserts M2M through-rows and
    changes no existing column, so no saved data is lost or overwritten.
    """
    db_alias = schema_editor.connection.alias
    for name in _ENQUIRY_MODELS:
        Model = apps.get_model('entries', name)
        qs = Model.objects.using(db_alias).exclude(insurance_company__isnull=True)
        for row in qs.iterator():
            row.compared_insurance_companies.add(row.insurance_company_id)


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0043_entryremark_kind_generalnewentry_is_voided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewentry',
            name='compared_insurance_companies',
            field=models.ManyToManyField(blank=True, related_name='general_new_compared', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='generalrenewalentry',
            name='compared_insurance_companies',
            field=models.ManyToManyField(blank=True, related_name='general_renewal_compared', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorfleetnewentry',
            name='compared_insurance_companies',
            field=models.ManyToManyField(blank=True, related_name='motor_fleet_new_compared', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorfleetrenewalentry',
            name='compared_insurance_companies',
            field=models.ManyToManyField(blank=True, related_name='motor_fleet_renewal_compared', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motornewentry',
            name='compared_insurance_companies',
            field=models.ManyToManyField(blank=True, related_name='motor_new_compared', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorrenewalentry',
            name='compared_insurance_companies',
            field=models.ManyToManyField(blank=True, related_name='motor_renewal_compared', to='entries.insurancecompany'),
        ),
        # Preserve every existing enquiry's insurer in the new multi-select
        # field. Reverse is a no-op: rolling back drops the M2M table anyway.
        migrations.RunPython(backfill_compared_insurers, migrations.RunPython.noop),
    ]
