# Generated by Django 4.2.27 on 2026-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0044_compared_insurance_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalnewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generalnewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generalrenewalentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalrenewalstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generalrenewalstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetnewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetnewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetnewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetrenewalentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetrenewalstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorfleetrenewalstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motornewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='motornewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motornewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorrenewalentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorrenewalstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='motorrenewalstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('retained', 'Retained'), ('lost', 'Lost'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
