# Generated by Django 4.2.27 on 2026-07-13 07:05

from django.db import migrations, models
import django.db.models.deletion


# TED-592 (corrected): each enquiry model's "Won" status. New enquiries close as
# 'converted'; renewals close as 'retained'.
WON_STATUS_BY_MODEL = [
    ('GeneralNewEntry', 'converted'),
    ('GeneralRenewalEntry', 'retained'),
    ('MotorNewEntry', 'converted'),
    ('MotorRenewalEntry', 'retained'),
    ('MotorFleetNewEntry', 'converted'),
    ('MotorFleetRenewalEntry', 'retained'),
]


def backfill_converted_insurer(apps, schema_editor):
    """Enquiries already Won under the previous design stored the purchased
    insurer in `insurance_company`. Copy that value into the new
    `converted_insurer` for those Won rows so history still displays correctly.
    `insurance_company` is never modified."""
    for model_name, won_status in WON_STATUS_BY_MODEL:
        Model = apps.get_model('entries', model_name)
        Model.objects.filter(
            status=won_status, insurance_company__isnull=False,
        ).update(converted_insurer=models.F('insurance_company'))


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0048_marine_new_revamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewentry',
            name='converted_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_new_converted', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='generalrenewalentry',
            name='converted_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_renewal_converted', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorfleetnewentry',
            name='converted_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_fleet_new_converted', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorfleetrenewalentry',
            name='converted_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_fleet_renewal_converted', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motornewentry',
            name='converted_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_new_converted', to='entries.insurancecompany'),
        ),
        migrations.AddField(
            model_name='motorrenewalentry',
            name='converted_insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motor_renewal_converted', to='entries.insurancecompany'),
        ),
        migrations.RunPython(backfill_converted_insurer, migrations.RunPython.noop),
    ]
