# Generated by Django 4.2.27 on 2026-07-13 08:53
# TED-656: 'In Progress' is removed from Marine New — 'Shared With Client' is its
# replacement. Remap any existing enquiry currently at 'in_progress' onto
# 'shared_with_client' so it stays active (the state machine no longer offers
# 'in_progress' as a target, so an un-migrated row would have no valid next
# step). MarineNewStatusTransition history rows are deliberately left untouched
# to preserve the audit trail.

from django.db import migrations, models


def remap_in_progress_to_shared(apps, schema_editor):
    MarineNewEntry = apps.get_model('entries', 'MarineNewEntry')
    MarineNewEntry.objects.filter(status='in_progress').update(
        status='shared_with_client'
    )


def noop_reverse(apps, schema_editor):
    # Irreversible: once remapped we can't distinguish an originally
    # 'shared_with_client' enquiry from one that was 'in_progress'.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0049_converted_insurer'),
    ]

    operations = [
        migrations.RunPython(remap_in_progress_to_shared, noop_reverse),
        migrations.AlterField(
            model_name='marinenewentry',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('shared_with_client', 'Shared With Client'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='marinenewstatustransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New Enquiry'), ('shared_with_client', 'Shared With Client'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marinenewstatustransition',
            name='to_status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('shared_with_client', 'Shared With Client'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('lost', 'Lost')], max_length=20),
        ),
    ]
